services:

  frontend:
    image: '${DOCKER_IMAGE_FRONTEND?Variable not set}:latest'
    build:
      context: ./frontend
      target: build-stage
      args:
        - NODE_ENV=development
        - VITE_API_URL=${VITE_API_URL}
        - VITE_POST_LOGOUT_REDIRECT=${VITE_POST_LOGOUT_REDIRECT}
    restart: "no"
    networks:
      - traefik-public
      - default
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: [ "npm", "run", "dev" ]

  backend:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:latest'
    build:
      context: ./backend
      target: production
    restart: "no"
    networks:
      - traefik-public
      - default
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/v1/health" ]
      interval: 30s
      timeout: 5s
      retries: 5

  db:
    image: postgres:16.2
    restart: "no"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?unset}
      - POSTGRES_USER=${POSTGRES_USER?unset}
      - POSTGRES_DB=${POSTGRES_DB?unset}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
  
volumes:
  app-db-data:

networks:
  traefik-public:
    external: false
