import AppShell from '@/components/AppShell'

function Home() {
  return (
    <AppShell>
      <div className="bg-white font-body text-shire-dark">
        {/* Hero Section */}
        <section className="mx-auto max-w-5xl px-6 py-24 text-center">
          <h1 className="mb-4 font-heading text-5xl md:text-6xl">Quest-Lock</h1>
          <p className="mb-8 text-xl text-shire-bark md:text-2xl">
            Don't just delete your account. Lock it behind a real-world
            adventure that you design.
            <br />
            The only key is your commitment.
          </p>
          <button className="rounded-full bg-shire-sun px-6 py-3 font-ui text-lg text-shire-dark shadow-lg transition hover:bg-shire-bark hover:text-shire-light">
            Begin Your Quest
          </button>
        </section>

        {/* Flow Section */}
        <section className="bg-shire-stone py-20">
          <div className="mx-auto max-w-4xl space-y-16 px-6">
            {/* Step 1: Generate & Split Your Password */}
            <div className="flex flex-col items-center gap-8 md:flex-row-reverse">
              <div className="flex-1">
                <h2 className="mb-2 font-heading text-3xl">
                  1. Generate & Split Your Password
                </h2>
                <p>
                  Our app generates a new, highly secure password on your
                  device. Using Shamir&apos;s Secret Sharing, this password is
                  immediately split into 10 encrypted shares. You are given 5 of
                  these shares to hold locally—not enough to unlock the account
                  on your own.
                </p>
              </div>
              <div className="flex-1">
                <img
                  src="/images/split-keys.png"
                  alt="Splitting password shares"
                  className="rounded-xl shadow-lg"
                />
              </div>
            </div>

            {/* Step 2: Design Your Quests */}
            <div className="flex flex-col items-center gap-8 md:flex-row">
              <div className="flex-1">
                <h2 className="mb-2 font-heading text-3xl">
                  2. Design Your Quests
                </h2>
                <p>
                  You choose how to lock the other 5 shares on our server.
                  Assign each share a unique quest. Lock them behind real-world
                  GPS locations, set a time-delay, create a paywall, or even
                  give one to a trusted friend. You set the difficulty and the
                  adventure.
                </p>
              </div>
              <div className="flex-1">
                <img
                  src="/images/lock-chest.png"
                  alt="Designing quests for password shares"
                  className="rounded-xl shadow-lg"
                />
              </div>
            </div>

            {/* Step 3: Lock Your Social Media */}
            <div className="flex flex-col items-center gap-8 md:flex-row-reverse">
              <div className="flex-1">
                <h2 className="mb-2 font-heading text-3xl">
                  3. Lock Your Social Media
                </h2>
                <p>
                  With your quests in place, you&apos;ll change your social
                  media password to the new one generated by Quest-Lock. Once
                  you log out, the account is officially locked. Since the full
                  password is unknown to everyone (including you and us), casual
                  access is impossible.
                </p>
              </div>
              <div className="flex-1">
                <img
                  src="/images/confirm-lock.png"
                  alt="Locking the social media account"
                  className="rounded-xl shadow-lg"
                />
              </div>
            </div>

            {/* Step 4: Embark on a Quest */}
            <div className="flex flex-col items-center gap-8 md:flex-row">
              <div className="flex-1">
                <h2 className="mb-2 font-heading text-3xl">
                  4. Embark on a Quest
                </h2>
                <p>
                  To start your recovery, you must complete the quests you
                  designed. For a geographic quest, travel to the location and
                  use our app to prove you&apos;re there with a GPS check-in and
                  a landmark photo. Our server validates your proof and releases
                  one share.
                </p>
              </div>
              <div className="flex-1">
                <img
                  src="/images/quest-map.png"
                  alt="Completing real-world quests"
                  className="rounded-xl shadow-lg"
                />
              </div>
            </div>

            {/* Step 5: Reconstruct & Regain Access */}
            <div className="flex flex-col items-center gap-8 md:flex-row-reverse">
              <div className="flex-1">
                <h2 className="mb-2 font-heading text-3xl">
                  5. Reconstruct & Regain Access
                </h2>
                <p>
                  Once you&apos;ve collected the required number of shares
                  (e.g., 6 out of 10), you can reconstruct the original
                  password. You can now use this password and regain access to
                  your social media account.
                </p>
              </div>
              <div className="flex-1">
                <img
                  src="/images/unlock-success.png"
                  alt="Successfully reconstructing password"
                  className="rounded-xl shadow-lg"
                />
              </div>
            </div>
          </div>
        </section>

        {/* Call to Action */}
        <section className="py-20 text-center">
          <h2 className="mb-4 font-heading text-4xl">
            Give Your Willpower a Boost
          </h2>
          <p className="mx-auto mb-6 max-w-xl">
            Quest-Lock makes recovery possible — but only if you really want it.
            No more accidental logins or broken detox promises.
          </p>
          <button className="rounded-full bg-shire-sun px-8 py-3 font-ui text-lg text-shire-dark shadow transition hover:bg-shire-bark hover:text-shire-light">
            Start Your Journey
          </button>
        </section>
      </div>
    </AppShell>
  )
}

export default Home
