name: Deploy Frontend to Cloudflare Pages

on:
  push:
    branches: ['main']
    paths:
      - 'frontend/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: './frontend/.nvmrc'

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Run build
        run: npm run build
        working-directory: ./frontend

      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ vars.CLOUDFLARE_PAGES_FRONTEND_PROJECT }}
          directory: ./frontend/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}